# Generated by Django 4.1.3 on 2022-11-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_usercustom_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustom',
            name='state',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
