# Generated by Django 4.1.3 on 2022-11-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_sabad_p2'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('textmessage', models.TextField()),
                ('response', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contact',
            },
        ),
    ]
