# Generated by Django 4.1.3 on 2022-11-07 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_offer',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.offer'),
        ),
    ]
